In [1]:
#Student ID: 700755588
#       CRN :23476

#Question 1

class Employee:
    countofNoEmp = 0  #help in the count of employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.countofNoEmp += 1  #  the employees count is incremented

    @staticmethod
    def average_salary(employees):
        total_salary = sum(employee.salary for employee in employees)
        return total_salary /len(employees)

class FulltimeEmployee(Employee):
    pass


e1 = Employee("Sai", "Sai Family",87, "Food")
e2 = Employee("kushi", "kushi  Family", 75, "business")


fulltime_e1 = FulltimeEmployee("dgsk", "dgsk Family", 88, "Farming")
fulltime_e2 = FulltimeEmployee("sai", "sai's Family", 78, "Fancy")


employees = [e1, e2, fulltime_e1, fulltime_e2]
avg_sal = Employee.average_salary(employees)

print("Count of Number of Employees:", Employee.countofNoEmp)
print("Average Salary of a Employee:", avg_sal)

Count of Number of Employees: 4
Average Salary of a Employee: 82.0


In [2]:
#Student ID: 700758588
#       CRN :23476

import numpy as np


random_vector = np.random.uniform(1, 20, 20)


reshaped_array = random_vector.reshape(4, 5)


reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Original random vector:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)

Original random vector:
[ 9.25859241  0.         16.10145406  4.37245936  6.85605385  8.83995207
  0.          3.0211853   8.55672485  6.31446439  0.         11.63464104
 19.01257854  9.65742336 10.83548909  9.81891204  0.          2.53821367
  7.60977333  6.95430052]

Reshaped array:
[[ 9.25859241  0.         16.10145406  4.37245936  6.85605385]
 [ 8.83995207  0.          3.0211853   8.55672485  6.31446439]
 [ 0.         11.63464104 19.01257854  9.65742336 10.83548909]
 [ 9.81891204  0.          2.53821367  7.60977333  6.95430052]]
